import type { AppProps } from "next/app";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: 'MuseOFF',
  description: 'Generated by create next app',
}

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <SessionProvider session={pageProps.session}>
      <Component {...pageProps} />
    </SessionProvider>
  );
}

export default MyApp;