import ToasterContext from '@/context/ToasterContext'
import '../app/globals.css'
import { Poppins } from 'next/font/google'

const inter = Poppins({
  subsets: ['latin-ext'],
  weight: '400',

})

export const metadata = {
  title: 'MuseOff',
  description: 'Generated by nosotros.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterContext />
        {children}
      </body>
    </html>
  )
}