import ToasterContext from '@/context/ToasterContext'
import '../app/globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MuseOff',
  description: 'Generated by nosotros.',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterContext />
        {children}
        </body>
    </html>
  )
}